services:
  - type: web
    name: medicare-hms
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /ready
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
